CREATE SEQUENCE id_seq_permission AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE permission (
  id        INTEGER      GENERATED BY DEFAULT AS SEQUENCE id_seq_permission PRIMARY KEY,
  name      VARCHAR(255) UNIQUE NOT NULL
);

-- Insert DATA to the permission table as you need here (I preffer to use this script to insert data because in
-- production mode I would insert it at this very time but if you're just running tests, you can use the data.sql file
-- to insert data and not this file, feel free to use it the way you want...)

-- AUDIT permissions
INSERT INTO permission (name) VALUES ('audit:read'), ('audit:write'), ('audit:delete')
