CREATE SEQUENCE id_seq_role_permission AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE role_permission (
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE id_seq_role_permission PRIMARY KEY,
  role_id       INTEGER NOT NULL,
  permission_id INTEGER NOT NULL
);

ALTER TABLE role_permission ADD FOREIGN KEY (role_id) REFERENCES PUBLIC.role(id);
ALTER TABLE role_permission ADD FOREIGN KEY (permission_id) REFERENCES PUBLIC.permission(id);