CREATE SEQUENCE id_seq_user_permission AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE user_permission (
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE id_seq_user_permission PRIMARY KEY,
  user_id       INTEGER NOT NULL,
  permission_id INTEGER NOT NULL
);

ALTER TABLE user_permission ADD FOREIGN KEY (user_id) REFERENCES PUBLIC.user(id);
ALTER TABLE user_permission ADD FOREIGN KEY (permission_id) REFERENCES PUBLIC.permission(id);